### ISSUE TITLE
ISDR: App Icon

### ISSUE THREAD

**Issue by Rajia** [isenseDev/iOS#72]
Make the changes that Mike suggested (see below) for the app icon.

- The "iS" part is a very bluish-yellow.  Could that be more of a solid yellow, closer to the yellow of the die color?
- The icon looks more wide than tall.  It may need to be square (e.g. 512x512 px)
- The dice should be shrunk down and moved to the upper right of the "iS".  See examples of our Android icons at https://play.google.com/store/apps/developer?id=Engaging+Computing+Group,+UML

**Comment by Rajia** [comment]
@stowellm I made the changes to the icon that you asked for! Can you please take a look and give me some feedback when you get a chance?
![is 1](https://cloud.githubusercontent.com/assets/4601144/5750036/e6a13bf2-9c1c-11e4-8fab-18d487282613.png)

**Comment by stowellm** [comment]
Looks much better! Only recommendation now is to make the "iS" a little larger and dice a little smaller, like the proportions in this icon:
![is_pictures_logo](https://cloud.githubusercontent.com/assets/1039162/5758177/d411bd26-9c90-11e4-9aa4-8fe148ffc5e0.png)

**Comment by Rajia** [comment]
@stowellm  Hope this looks better! Please let me know, so I can close this issue. 
![isdr_logo120](https://cloud.githubusercontent.com/assets/4601144/5790042/f9c98eca-9e54-11e4-8fcc-457d89e821dd.png)

**Comment by Rajia** [comment]
![isense_logo](https://cloud.githubusercontent.com/assets/4601144/5790043/0c0b6e32-9e55-11e4-817b-2bf498d20082.png)

**Comment by bdonald25** [comment]
@Rajia I recommend using a flat font like the android one. iOS tends to favor flat over 3D.

**Comment by Rajia** [comment]
Thanks for the feedback @bdonald25 . Do you know what the name of the font is?

**Comment by bdonald25** [comment]
@Rajia I am not sure sorry. I only have the .png file so I have no way to check.

**Comment by bdonald25** [comment]
@asalani93 Made the Android icons for Motion and Writer. Maybe he could help.

**Comment by Rajia** [comment]
No Problem @bdonald25 , thanks anyway! I choose a font that looks as close as possible. How does this look? @stowellm  do you approve?

![non3d](https://cloud.githubusercontent.com/assets/4601144/5801562/867556f4-9fba-11e4-8a0f-b017d091b19d.png)

**Comment by bdonald25** [comment]
Looks good!

**Comment by stowellm** [comment]
Approved- go ahead and add that to the app.

**Comment by Rajia** [comment]
Awesome, thanks guys!
