### ISSUE TITLE
ISDR: Bug with Select Project Button 

### ISSUE THREAD

**Issue by Rajia** [isenseDev/iOS#73]
If you click the select project button before using the app, it says project has incorrect credentials.

**Comment by Rajia** [comment]
This has been temporarily fixed using a hack. Still needs to be actually fixed. 

Notes:
A problem is somehow occurring where the default project is not being set until the roll button is clicked.

**Comment by Rajia** [comment]
Fixed. The issue was that use:dev was not being set to true originally.

**Comment by stowellm** [comment]
@Rajia - I'm re-opening this issue for now.  When you submit a pull request, reference this issue in it.  Then we'll close the issue once your code is merged in.

**Comment by Rajia** [comment]
Okay!

Sent from my iPhone

On Mar 26, 2015, at 1:55 PM, Mike Stowell <notifications@github.com<mailto:notifications@github.com>> wrote:


@Rajia<https://github.com/Rajia> - I'm re-opening this issue for now. When you submit a pull request, reference this issue in it. Then we'll close the issue once your code is merged in.

-
