### ISSUE TITLE
ISDR: Enhancements

### ISSUE THREAD

**Issue by Rajia** [isenseDev/iOS#85]
As of right now, the app is in proper working condition. However, before releasing to the iOS app store the following things should be completed:

- [x] Orientation Lock needs to be placed so app should only work in portrait mode
- [x] There shouldn't be labels, the writing should be on the buttons. 
- [x] Selecting a Project through browse needs to update project number on main screen.
- [x] Once a project is selected from the browse search bar, it should not close the whole project screen only the browse feature.  
- [x] Things need to align automatically

**Comment by stowellm** [comment]
@Rajia - I'm re-opening this issue for now.  When you submit a pull request, reference this issue in it.  Then we'll close the issue once your code is merged in.
